name: Update Dependencies

on:
  schedule:
    - cron:  '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Update dependencies with Maven
        run: mvn --batch-mode versions:use-latest-releases -DprocessDependencyManagement=false

      - name: Build with Maven
        run: mvn --batch-mode install

      - name: Commit if changes
        uses: stefanzweifel/git-auto-commit-action@v4